
### Spj3psSa

POST http://localhost:10155/pay
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
#x-session-id: 	session-72d7cb55-dcfa-4882-a229-9c44b90cbd83

{
  "taxRegime": "SelfAssessment",
  "reference": "1234567895",
  "amountInPence": 123,
  "vendorJourneyId": "some-vendor-id",
  "backURL": "https://www.someBackUrl.com"
}
