
### Spj3psSa

POST http://localhost:10156/pay
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "taxRegime": "SelfAssessment",
  "reference": "1234567891",
  "amountInPence": 123,
  "backURL": "https://www.someBackUrl.com",
  "dueDate": "2025-01-31"
}
