### Spj3psVat

POST http://localhost:10156/pay
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "taxRegime": "Vat",
  "reference": "101747645",
  "amountInPence": 123,
  "friendlyName": "Test Company",
  "backURL": "https://www.someBackUrl.com",
  "dueDate": "2025-04-30"
}
