### Friendly name field contains invalid character, causes bespoke error message

POST http://localhost:10156/pay
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json

{
  "taxRegime": "SelfAssessment",
  "reference": "1234567891",
  "amountInPence": 123,
  "friendlyName" : "ThisStringContainsAnInvalidCharacter%"
}
