openapi: "3.0.3"

info:
  version: 1.0.0
  title: HMRC third party payments
  description: |
    This API allows users to trigger an HMRC payment journey from their software. 
    
    The workflow enables an API user to redirect a customer through to an HMRC payment journey. 
    If an optional back-url was provided by the API user we will offer this as a link to the customer to continue their journey.
    
    Additional details about the outcome of the payment can be discovered 
    by the API user by taking advantage of the /status endpoint.

    Typical lifetimes for journey storage are not yet determined.

servers:
  - url: https://test-api.service.hmrc.gov.uk/payments/make-payment
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/payments/make-payment
    description: Production

components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            status: Update the status of fraud check
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: [ "application/vnd.hmrc.1.0+json" ]
      required: true
    contentTypeJsonHeader:
      name: "Content-Type"
      in: header
      description: |
        Specifies the format of the request body, which must be JSON.
      schema:
        type: string
        enum:
          - "application/json"
      required: true
    authorizationHeader:
      name: "Authorization"
      in: header
      description: |
        An OAuth 2.0 Bearer Token.
      schema:
        type: string
        example: Bearer bb7fed3fe10dd235a2ccda3d50fb
      required: true

paths:
  /pay:
    post:
      summary: Begin a payment journey.
      description: |
        After a successful call to the /pay endpoint, the API user receives JSON with a redirection URL. The API user
        then redirects the customer's browser to this URL, starting the payment journey.
      security:
        - applicationRestricted: [ ]
      requestBody:
        description: |
          The request body always contains the fields that allow HMRC to identify the liability that is being paid, so 
          that the funds are not mis-allocated. The required fields are the taxRegime, the paymentReference, the amountInPence, dueDate and 
          a journey identifier called the clientJourneyId.
          
          The taxRegime field identifies the tax being paid. Currently supported regimes are: Self Assessment.
          
          The paymentReference is the reference supplied by HMRC when the liability arose.
          
          The amountInPence is an integer number of pennies that must be greater than 0.  
          
          The clientJourneyId field is a UUID (version 4, variant 2) that is supplied by the API user in order to identify 
          the journey in calls to the /status endpoint.
          
          The API user can optionally supply a due date for the liability. This enables the user to setup a scheduled, future dated payment.
          This date must be in the future in format YYYY-MM-DD and cannot be today's date.
          
          The API user can optionally supply an additional URL.
          
          A backURL enables HMRC to display a link to the user to allow them to return to their software.

        required: true
        content:
          application/json:
            schema:
              title: Pay request schema
              description: The JSON describing an HMRC third party payment /pay payload.
              type: object
              required: [ clientJourneyId, taxRegime, paymentReference, amountInPence ]
              properties:
                clientJourneyId:
                  description: The client identifier for this journey. Must be a UUID (version 4, variant 2).
                  type: string
                  format: uuid
                  example: a218f71d-9bf2-438e-851c-71d50866c2e9
                taxRegime:
                  type: string
                  description: The tax regime under which the liability has arisen. One of a fixed set.
                  enum: [ SelfAssessment ]
                  example: SelfAssessment
                paymentReference:
                  description: The reference identifying the tax liability, penalty or interest payment. For self assessment this is the SA UTR and is 10 digits long.
                  type: string
                  example: 1097172564
                amountInPence:
                  description: The amount to be paid in pennies, so £12.34 is 1234, must be greater than 0.
                  type: number
                  minimum: 0
                  exclusiveMinimum: true
                  "multipleOf": 1
                  example: 1234
                dueDate:
                  description: The due date of the liability in format YYYY-MM-DD, an optional date in the future, not today.
                  type: string
                  format: date
                  example: 2024-12-30
                backURL:
                  description: If this is present HMRC will offer this as a link to the customer at the end of the journey.
                  type: string
                  format: uri
                  example: "https://some-accounting-software.com/after-pay/a218f71d9bf2438e851c71d50866c2e9"

      responses:
        201:
          description: Created. Body contains url to redirect user to.
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectURL:
                    type: string
                    description: The URL to direct the customer browser to in order to initiate the customer payment journey
              example:
                { "redirectURL": "https://tax.gov.uk/payments/start/jhdugiuygdwuygsxajvbh" }

        400:
          description: |
            Bad Request.
            
            A 400 response represents a malformed request. The returned JSON will attempt to guide
            the API user to the problem.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error field contains the error message.
              example:
                { "error": "Mandatory paymentReference field was omitted." }

        500:
          description: An error occurred upstream and could not be recovered from.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error field contains the error message.
              example:
                { "error": "Error from upstream" }

  /status:
    get:
      summary: Discover the status of a payment.
      description: |
        The API user can check the payment status by providing the clientJourneyId used 
        when the payment journey was created.
        The JSON body returned will include the clientJourneyId, the taxRegime, the paymentReference, the amountInPence paid and also the paymentStatus. 
        *NOTE* the paymentStatus is a fixed enum, with scheduled meaning the payment has not been taken, but has been scheduled to be taken at a future date chosen by the user.

      security:
        - applicationRestricted: [ ]

      parameters:

        - in: query
          name: clientJourneyId
          required: true
          description: The client's identifier for the journey.
          schema:
            type: string
            example: "a218f71d-9bf2-438e-851c-71d50866c2e9"

      responses:
        200:
          description: |
            A payment matching the query was found and the details returned in the JSON response
          content:
            application/json:
              schema:
                type: object
                required: [ clientJourneyId, taxRegime, paymentReference, amountInPence, paymentStatus ]
                properties:
                  clientJourneyId:
                    type: string
                    description: The client's identifier for the journey/payment.
                    example: "a218f71d-9bf2-438e-851c-71d50866c2e9"

                  taxRegime:
                    type: string
                    description: The tax regime under which the liability has arisen. One of a fixed set.
                    enum: [ SelfAssessment ]
                    example: "SelfAssessment"

                  paymentReference:
                    type: string
                    description: The reference identifying the tax liability.
                    example: "1097172564"

                  amountInPence:
                    description: Represents the amount actually paid, in pence.
                    type: integer
                    example: 3456

                  paymentStatus:
                    description: The status of the payment within the HMRC system.
                    type: string
                    enum: [ Completed, Failed, Cancelled, Scheduled ]
                    example: "Completed"
              example:
                {
                  "clientJourneyId": "a218f71d-9bf2-438e-851c-71d50866c2e9",
                  "taxRegime": "SelfAssessment",
                  "paymentReference": "1097172564",
                  "amountInPence": 1453,
                  "paymentStatus": "Completed"
                }
        400:
          description: |
            A malformed request. The returned JSON will attempt to guide
            the API user to the problem.

          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: |
                      An error containing what may be wrong with the request.
              example:
                { "error": "Mandatory clientJourneyId field of query was omitted." }
        404:
          description: |
            Either the payment journey never existed, or HMRC no longer has a record of the journey.
