openapi: "3.0.3"

info:
  version: 1.0.0
  title: HMRC third party payments
  description: |
    This API accepts payments from outside of HMRC. 
    
    The workflow enables an API user to redirect a customer through to an HMRC payment journey. 
    If an optional back-url was provided by the API user we will offer this as a link to the customer to continue their journey.
    
    Additional details about the outcome of the payment can be discovered 
    by the API user by taking advantage of the /status endpoint.

    Typical lifetimes for journey storage are not yet determined.

servers:
  - url: https://test-api.service.hmrc.gov.uk/payments/make-payment
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/payments/make-payment
    description: Production

components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            status: Update the status of fraud check
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
  parameters:
    acceptHeader:
      name: Accept
      in: header
      schema:
        type: string
        enum: ["application/vnd.hmrc.1.0+json"]
      required: true

paths:
  /pay:
    post:
      summary:  Begin a payment journey.
      description: |
        After a successful call to the /pay endpoint, the API user receives JSON with a redirection URL. The API user
        then redirects the customer's browser to this URL, starting the payment journey.


      requestBody:
        description: |
          The request body always contains the fields that allow HMRC to identify the liability that is being paid, so 
          that the funds are not mis-allocated. The necessary fields are the taxRegime, the reference, the amountInPence, and 
          a journey identifier called the vendorJourneyId.
          
          The taxRegime field identifies the tax being paid, Self Assessment, Corporation Tax, VAT, and 
          Employers' Pay As You Earn are supported.
          
          The reference is the reference supplied by HMRC when the liability arose.
          
          The amountInPence is an integer number of pennies that must be greater than 0.
          
          The vendorJourneyId field is a UUID (version 4, variant 2) that is supplied by the API user in order to identify 
          the journey in calls to the /status endpoint.
          
          The API user can optionally supply an additional URL.
          
          If the backURL field is supplied, this URL will be displayed as a link to the customer
          at the end of the customer's journey to conveniently return to the API user's 
          systems.

        required: true
        content:
          application/json:
            schema:
              title: Pay request schema
              description: The JSON describing an HMRC third party payment /pay payload.
              type: object
              required: [ taxRegime, reference, amountInPence, vendorJourneyId ]
              properties:
                taxRegime:
                  type: string
                  description: The tax regime under which the liability has arisen. One of a fixed set.
                  enum: [ SelfAssessment, Vat, CorporationTax, EmployersPayAsYouEarn ]
                  example: SelfAssessment

                reference:
                  description: The reference identifying the tax liability.
                  type: string
                  example: 1097172564

                amountInPence:
                  description: The amount to be paid in pennies, so £12.34 is 1234, must be greater than 0.
                  type: number
                  minimum: 0
                  exclusiveMinimum: true
                  example: 1234

                vendorJourneyId:
                  description: Your identifier for this journey. Must be a UUID (version 4, variant 2).
                  type: string
                  format: uuid
                  example: a218f71d-9bf2-438e-851c-71d50866c2e9

                backUrl:
                  description: If this is present HMRC will offer this as a link to the customer at the end of the journey.
                  type: string
                  format: uri
                  example: "https://some-accounting-software.com/after-pay/a218f71d9bf2438e851c71d50866c2e9"


      responses:
        201:
          description: Created. Body contains url to redirect user to.
          content:
            application/json:
              schema:
                type: object
                properties:
                  redirectURL:
                    type: string
                    description: The URL to direct the customer browser to initiate the customer payment journey
              example:
                {"redirectURL": "https://tax.gov.uk/payments/start/jhdugiuygdwuygsxajvbh"}

        400:
          description: |
            Bad Request.
          
            A 400 response represents a malformed request. The returned JSON will attempt to guide
            the API user to the problem.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error field contains the error message.
              example:
                {"error": "Mandatory reference field was omitted."}

        500:
            description: An error occurred upstream
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      description: The error field contains the error message.
                example:
                  { "error": "Error from upstream" }

  /status:
    get:
      summary: Discover the status of a payment.
      description: |
        The API user can check the payment status by providing the tax-regime and reference used 
        when the payment journey was created. The JSON returned will repeat these three fields and add
        the amount that the customer actually paid. *Note* that the amount can be zero in the return denoting that no money
        was sent to HMRC because the journey has not completed in a standard way. This can arise from
        a number of situations but HMRC will not provide any further information.

      parameters:
        - in: query
          name: reference
          required: true
          description: The reference as originally provided by HMRC.
          schema:
            type: string
            example: 1097172564

        - in: query
          name: taxReference
          description: The tax regime. One of a fixed set.
          schema:
            type: string
            example: SelfAssessment
            enum: [ SelfAssessment, Vat, CorporationTax, EmployersPayAsYouEarn ]

      responses:
        200:
          description: |
            A payment matching the query was found and the details returned in the JSON response
          content:
            application/json:
              schema:
                type: object
                properties:
                  taxRegime:
                    type: string
                    description: The tax regime under which the liability has arisen. One of a fixed set.
                    enum: [ SelfAssessment, Vat, CorporationTax, EmployersPayAsYouEarn ]

                  reference:
                    type: string
                    description: The reference identifying the tax liability.
                    example: 1097172564

                  amountInPence:
                    description: Represents the amount actually paid. It may be zero.
                    type: integer
                    minimum: 0
                    exclusiveMinimum: false
                    example: 3456

              example:
                {
                  "taxRegime": "SelfAssessment",
                  "reference": "1097172564",
                  "amountInPence": 1453
                }
        400:
          description: |
            A malformed request. The returned JSON will attempt to guide
            the API user to the problem.

          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The url to direct the customer browser to, to initiate the customer payment journey
              example:
                {
                  "error": "Mandatory ref field of query was omitted."
                }
        404:
          description: |
            Either the payment journey never existed, or HMRC no longer has a record of the journey.
